config/routes.rb
Rails.application.routes.draw do

    devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: "users/registrations"
    }

    # devise_for :admins, :controllers => { :registrations => :registrations }
    devise_for :admins, :skip => [:registrations]

    devise_scope :admin do
      get "/signin" => "devise/sessions#new", :as => "signin" # custom path to login/sign_in
    end

    devise_scope :user do
      get "/sign_in" => "devise/sessions#new", :as => "sign_in" # custom path to login/sign_in
      get "/sign_up" => "devise/registrations#new", :as => "sign_up" # custom path to login/sign_in
      get "users/verify/" => 'users/registrations#show_verify', as: 'verify'
      post "users/verify"
      post "users/resend"
    end

    as :admin do
      get 'admins/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'
      put 'admins' => 'devise/registrations#update', :as => 'admin_registration'
      patch 'admins' => 'devise/registrations#update', :as => 'update_admin_registration'
    end

    namespace :admin do
      root "dashboards#index"
      get 'dashboards' => "dashboards#index", :as => "dashboard"
      get 'invoices/:id' => 'orders#invoice', as: "invoice"

      resources :users
      resources :admins
      resources :categories
      resources :blogs
      resources :settings, only: [:index, :new, :update, :create, :edit]
    end

    get 'under_construction' => "static_pages#under_construction", as: "under_construction"
    root 'static_pages#index'
    resources :blogs, only: [:index, :show]
    resources :categories, only: [:index, :show]
    resources :tags, only: [:show]
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  attr_writer :login

  after_initialize :set_default_role, :if => :new_record?

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, authentication_keys: [:login]

  has_attached_file :photo, style: { medium: "300x500>",thumb: "100x100>" }
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

  has_many :users
  has_many :blogs
  has_many :categories

  validates :username, presence: :true, uniqueness: { case_sensitive: false }

  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true

  def login
    self.username || self.email
  end

  enum role: [:user, :vip, :admin, :employee, :delivery]

  def set_default_role
    self.role ||= :user
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  
  self.abstract_class = true

end

app/models/asset.rb
class Asset < ApplicationRecord
  belongs_to :admin, optional: true
  belongs_to :product

  has_attached_file :image, style: { medium: "300x500>",thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/blog.rb
class Blog < ApplicationRecord
  before_save :update_slug

  belongs_to :admin
  belongs_to :category
  has_many :tags, inverse_of: :blog
  accepts_nested_attributes_for :tags, :reject_if => :all_blank, :allow_destroy => true

  has_attached_file :image, styles: {
    medium: "470x500#",
    thumb: "80x80#",
    popular: "270x370#",
    trending: "270x300#",
    daily: "384x245#",
    explore: "270x200#",
    category: "205x160#"
  }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  def update_slug
    self.slug = title.parameterize
  end

  def to_param
    slug
  end

  def self.is_slide_active?
    where('is_slide = true')
  end

  def self.is_order_limit_one?
    order("created_at desc").limit(1)
  end

  def self.not_show_first_record
    where.not('id = 1').order('created_at desc').limit(8)
  end

end

app/models/category.rb
class Category < ApplicationRecord
  before_save :update_slug

  has_many :blogs
  belongs_to :admin

  def update_slug
    self.slug = category_name.parameterize
  end

  def to_param
    slug
  end
end

app/models/maintain.rb
class Maintain < ApplicationRecord
  belongs_to :setting

  SELECT_PAGE = [
    "None",
    "All",
    "static_pages",
    "products"
  ]

end

app/models/setting.rb
class Setting < ApplicationRecord
  has_many :maintains
  accepts_nested_attributes_for :maintains, :allow_destroy => true
end

app/models/tag.rb
class Tag < ApplicationRecord
  before_save :update_slug
  belongs_to :blog

  def update_slug
    self.slug = name.parameterize
  end

  def to_param
    slug
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  after_initialize :set_default_role, :if => :new_record?

  attr_writer :login

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, authentication_keys: [:login]

  # validates :username, presence: :true, uniqueness: { case_sensitive: false }

  # validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true

  belongs_to :admin, optional: true

  # phony_normalize :phone, default_country_code: 'KH'
  # validates :phone_numer, phony_plausible: true
  # validates :phone_number, uniqueness: true
  validates :phone_number, presence: true
  # validates :phone, numericality: true

  # def active_for_authentication?
  #   super and self.is_active?
  # end

  def login
    @login || self.phone_number || self.email
  end

  enum role: [:user, :seller, :customer]

  def set_default_role
    self.role ||= :user
  end

  def self.find_for_database_authentication(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions.to_h).where(["lower(phone_number) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      elsif conditions.has_key?(:phone_number) || conditions.has_key?(:email)
        where(conditions.to_h).first
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def time_format(datetime)
    datetime.strftime('%H:%M') unless datetime.blank?
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/commodities_helper.rb
module CommoditiesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/fast_cash_helper.rb
module FastCashHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pos_helper.rb
module PosHelper

  def display_change_in_usd (order)
    number_to_currency ((order.total_cash_in_riel - order.total * Constant::exchange_rate) / Constant::exchange_rate).to_i, precision: 0
  end

  def display_change_in_riel (order)
    n = (order.total_cash_in_riel - order.total * Constant::exchange_rate) / Constant::exchange_rate
    remain = n.to_s.split('.')
    return ('0.' + remain[1]).to_f * Constant::exchange_rate
  end

end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/admin/admins/_admin.html.erb
<tr class="delete_admin_<%=admin.id%>">
  <td id="data_<%=admin.id%>">
    <%=admin.id%>
  </td>
  <td>
    <%=admin.username%>
  </td>
  <td>
    <%=admin.email%>
  </td>
  <td>
    <%=time_ago(admin.created_at)%>
  </td>
  <td class="text-center">
    <%=form_for([:admin, admin], remote: true) do |f|%>
      <%=link_to admin_admin_path(admin), remote: true,class: "btn btn-primary", "data-target" => "bd-example-modal-lg-panhara" do %>
        View
      <%end%>
      <%=link_to edit_admin_admin_path(admin),id: "link_#{admin.id}",class: "btn btn-primary", remote: true do %>
        Edit
      <% end %>
    <%end%>
  </td>
</tr>

app/views/admin/admins/admin_error.js.erb
$("input#admin_email").val("");
$("input#admin_fullname").val("");
$("input#admin_organization").val("");
$("#admin-errors").html("<br><%= j render partial: 'layouts/flash_errors', locals: {flash: :flash}%>");

app/views/admin/admins/admin_success.js.erb
$("input#admin_email").val("");
$("input#admin_fullname").val("");
$("input#admin_organization").val("");
$("#admin-success").html("<br><%= j render partial: 'layouts/flash_success', locals: {flash: :flash}%>");

app/views/admin/admins/destroy.js.erb
$('.delete_admin_<%=@admin.id%>').remove();

app/views/shared/_footer.html.erb
<footer id="tg-footer" class="tg-footer tg-haslayout">
  <div class="tg-newsletter">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-5 col-lg-4">
          <div class="tg-borderleft">
            <span>Singup for Free!</span>
            <h3>Get Amazing &amp; New Information.</h3>
          </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-7 col-lg-8">
          <form class="tg-formtheme tg-formnewsletter">
            <fieldset>
              <div class="form-group">
                <input type="text" class="form-control" name="yourname" placeholder="Your Name">
              </div>
              <div class="form-group">
                <input type="text" class="form-control" name="yourname" placeholder="Your Name">
              </div>
              <button type="submit" class="tg-btn">Signup Now</button>
            </fieldset>
          </form>
        </div>
      </div>
    </div>
  </div>
  <div class="tg-threecolumns">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
          <div class="tg-column">
            <div class="tg-widget tg-widgetaboutus">
              <figure><img src="images/img-01.jpg" alt="image description"></figure>
              <h3>The Article</h3>
              <div class="tg-description">
                <p>Consectetur adipisicing elit sed eiusmod tempor incididunt ut labore et dolore magna aliqua enim ad minim veniam quis nostrud exercitation ullamco laboris.</p>
              </div>
              <ul class="tg-socialicons">
                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                <li><a href="#"><i class="fa fa-pinterest-p"></i></a></li>
                <li><a href="#"><i class="fa fa-instagram"></i></a></li>
              </ul>
              <div class="tg-btnbox">
                <a class="tg-btn" href="javascript:void(0);">Contact Now</a>
              </div>
            </div>
          </div>
        </div>
        <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
          <div class="tg-column">
            <div class="tg-widget tg-widgetcategories">
              <div class="tg-widgettitle">
                <h3>Popular Categories</h3>
              </div>
              <div class="tg-widgetcontent">
                <ul>
                  <%@categories.each do |category|%>
                  <li>
                    <%=link_to category_path(category) do%>
                      <span><%=category.category_name.capitalize%></span><%=category.blogs.count%>
                    <%end%>
                  </li>
                  <%end%>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
          <div class="tg-column">
            <div class="tg-widget tg-widgettrendingposts">
              <div class="tg-widgettitle">
                <h3>Editor Picks</h3>
              </div>
              <div class="tg-widgetcontent">
                <ul>
                  <%@editor_picks.each do |post|%>
                    <li>
                      <figure>
                        <%=link_to blog_path(post) do%>
                          <%= image_tag post.image.url(:thumb)%>
                        <%end%>
                        <a class="tg-btnview" href="#"></a>
                      </figure>
                      <div class="tg-trendingpostcontent">
                        <h4>
                          <%=link_to blog_path(post) do%>
                            <%= post.title.capitalize%>
                          <%end%>
                        </h4>
                        <time datetime="2016-02-02">April 27, 2017</time>
                        <span class="tg-postviews">2.4K Views</span>
                      </div>
                    </li>
                  <%end%>
                  <li>
                    <%=link_to "View All", blogs_path%>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="tg-footerbar">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <strong class="tg-logo"><a href="javascript:void(0);"><img src="images/logo2.png" alt="image description"></a></strong>
          <div class="tg-copyrightbox">
            <span>&copy; 2019 - The Article. All Rights Reserved</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_nav.html.erb
<header id="tg-header" class="tg-header tg-haslayout">
  <div class="tg-topbar">
    <div class="container">
      <div class="row">
        <div class="col-sm-12 col-xs-12">
          <div class="tg-rightbox">
            <ul class="tg-socialicons">
              <li><a href="#"><i class="fa fa-facebook"></i></a></li>
              <li><a href="#"><i class="fa fa-twitter"></i></a></li>
              <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
              <li><a href="#"><i class="fa fa-pinterest-p"></i></a></li>
              <li><a href="#"><i class="fa fa-instagram"></i></a></li>
            </ul>
            <ul>
              <li class="dropdown tg-themedropdown">
                <button class="tg-btndropdown" id="tg-logindropdown" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">login</button>
                <div class="tg-dropdownbox" aria-labelledby="tg-logindropdown">
                  <form class="tg-formtheme tg-formlogin">
                    <fieldset>
                      <h2>Welcome, Login to Your Account</h2>
                      <div class="form-group">
                        <input type="email" name="email" class="form-control" placeholder="Enter your Email" />
                      </div>
                      <div class="form-group">
                        <div class="tg-inputicon">
                          <input type="password" name="password" class="form-control tg-password" placeholder="Your Password" />
                          <i class="tg-btnshowpassword"></i>
                        </div>
                      </div>
                      <div class="form-group">
                        <span class="tg-checkbox">
                          <input type="checkbox" value="yes" id="tg-remember" />
                          <label htmlFor="tg-remember">Remember Me</label>
                        </span>
                        <a class="tg-btnforgot" href="javascript:void(0);">Forgot Password?</a>
                      </div>
                      <div class="form-group">
                        <button class="tg-btn" type="submit">Login</button>
                      </div>
                      <div class="tg-notebox">
                        <p>Don’t Have Account? <a href="javascript:void(0);">Create New Account</a></p>
                      </div>
                    </fieldset>
                  </form>
                </div>
              </li>
              <li class="dropdown tg-themedropdown">
                <button class="tg-btndropdown" id="tg-registerdropdown" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">register</button>
                <div class="tg-dropdownbox" aria-labelledby="tg-registerdropdown">
                  <form class="tg-formtheme tg-formlogin">
                    <fieldset>
                      <h2>Create New Account</h2>
                      <div class="form-group">
                        <input type="text" name="fullname" class="form-control" placeholder="Full Name" />
                      </div>
                      <div class="form-group">
                        <input type="text" name="phone" class="form-control" placeholder="Phone" />
                      </div>
                      <div class="form-group">
                        <input type="email" name="email" class="form-control" placeholder="Email* (Your email address will not be published.)" />
                      </div>
                      <div class="form-group">
                        <div class="tg-inputicon">
                          <input type="password" name="password" class="form-control tg-password" placeholder="Your Password" />
                          <i class="tg-btnshowpassword"></i>
                        </div>
                      </div>
                      <div class="form-group">
                        <button class="tg-btn" type="submit">Register Now</button>
                      </div>
                      <div class="tg-notebox">
                        <p>Already Have Account? <a href="javascript:void(0);">Login Now</a></p>
                      </div>
                    </fieldset>
                  </form>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="clearfix"></div>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-xs-12">
        <div class="tg-logoarea">
          <strong class="tg-logo"><a href="#"><img src="logo.png" /></a></strong>
          <div class="tg-addbox">
            <a href="/"><img src="images/placeholder/add-01-770x90.jpg" alt="" /></a>
          </div>
        </div>
        <div class="tg-navigationarea tg-navigationareamiddle">
          <nav id="tg-nav" class="tg-nav">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#tg-navigation" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
            </div>
            <div id="tg-navigation" class="collapse navbar-collapse tg-navigation">
              <ul>
                <li class="current-menu-item">
                  <a href="/">Home</a>
                </li>
                <li class="current-menu-item">
                  <%=link_to "News", blogs_path%>
                </li>
                <li class="menu-item-has-children megadropdown">
											<a style="color: black;" href="#">Post Types</a>
											<div class="sub-menu tg-tabsdropdown">
												<div class="tg-themetabstyle">
													<ul class="tg-tabnav" role="tablist">
                            <%@categories.limit(1).each do |category|%>
														  <li role="presentation" class="active">
                                <a href="#<%=category.category_name.downcase%>" aria-controls="<%=category.category_name.downcase%>" role="tab" data-toggle="tab">
                                  <%=category.category_name.capitalize%>
                                </a>
                              </li>
                            <%end%>
                            <%@categories.where.not(id: 1).each do |category|%>
														  <li role="presentation">
                                <a href="#<%=category.category_name.downcase%>" aria-controls="<%=category.category_name.downcase%>" role="tab" data-toggle="tab">
                                  <%=category.category_name.capitalize%>
                                </a>
                              </li>
                            <%end%>
                        	</ul>
													<div class="tab-content tg-tabcontent">
                            <%@categories.limit(1).each do |category|%>
														  <div role="tabpanel" class="tab-pane active" id="<%=category.category_name.downcase%>">
															  <h2><%=category.category_name.upcase%></h2>
  															<div class="tg-posts">
  																<div class="tg-tabsslider tg-megamenuslider">
                                    <%category.blogs.each do |blog|%>
  																	  <div class="item">
  																		  <article class="tg-post">
  																			<figure class="tg-postimg">
  																				<span class="tg-postfeatured"><i class="fa fa-bolt"></i></span>
  																				<%=link_to blog_path(blog) do%>
                                            <%=image_tag blog.image.url(:category)%>
                                          <%end%>
  																			</figure>
  																			<div class="tg-postcontent">
  																				<div class="tg-borderleft">
  																					<ul class="tg-posttags">
                                              <%blog.tags.limit(2).each do |tag|%>
                                                <li>
                                                  <%=link_to tag.name.capitalize, tag_path(tag)%>
                                                </li>
                                              <%end%>
  																					</ul>
  																					<div class="tg-posttitle">
  																						<h3>
                                                <%=link_to blog_path(blog) do%>
                                                  <%=blog.title.capitalize%>
                                                <%end%>
                                              </h3>
  																					</div>
  																				</div>
  																			</div>
  																		</article>
  																	  </div>
                                    <%end%>
  																</div>
  															</div>
														  </div>
                            <%end%>
                            <%@categories.where.not(id: 1).each do |category|%>
														  <div role="tabpanel" class="tab-pane" id="<%=category.category_name.downcase%>">
															  <h2><%=category.category_name.upcase%></h2>
  															<div class="tg-posts">
  																<div class="tg-tabsslider tg-megamenuslider">
                                    <%category.blogs.each do |blog|%>
  																	  <div class="item">
    																		<article class="tg-post">
    																			<figure class="tg-postimg">
    																				<span class="tg-postfeatured"><i class="fa fa-bolt"></i></span>
                                            <%=link_to blog_path(blog) do%>
                                              <%=image_tag blog.image.url(:category)%>
                                            <%end%>
                                          </figure>
    																			<div class="tg-postcontent">
    																				<div class="tg-borderleft">
    																					<ul class="tg-posttags">
                                                <%blog.tags.limit(2).each do |tag|%>
                                                  <li>
                                                    <%=link_to tag.name.capitalize, tag_path(tag)%>
                                                  </li>
                                                <%end%>
    																					</ul>
    																					<div class="tg-posttitle">
    																						<h3>
                                                  <%=link_to blog_path(blog) do%>
                                                    <%=blog.title.capitalize%>
                                                  <%end%>
                                                </h3>
    																					</div>
    																				</div>
    																			</div>
    																		</article>
  																	  </div>
                                    <%end%>
  																</div>
  															</div>
														  </div>
                            <%end%>
													</div>
												</div>
											</div>
										</li>
                <%@categories.each do |category|%>
                  <li class="current-menu-item">
                    <%=link_to category.category_name, category_path(category)%>
                  </li>
                <%end%>
              </ul>
            </div>
          </nav>
          <a id="tg-btnsearchtoggle" class="tg-btnsearchtoggle" href="#tg-search"><i class="lnr lnr-magnifier"></i></a>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/shared/_popular.html.erb
<div class="clearfix"></div>
<div class="tg-borderheading">
  <h3>What’s Popular</h3>
</div>
<div class="tg-postmargin tg-overflowvisible">
  <div class="row">
    <%@populars.each do |post|%>
      <div class="col-xs-6 col-sm-6 col-md-4 col-lg-4">
      <article class="tg-post">
        <figure class="tg-postimg">
          <span class="tg-postfeatured">
            <i class="fa fa-bolt"></i>
          </span>
          <%=link_to blog_path(post) do%>
            <%=image_tag post.image.url(:popular)%>
          <%end%>
          <a class="tg-btnview" href="#">view post</a>
          <ul class="tg-postmatadata">
            <li>
              <a href="javascript:void(0);">
                <span class="lnr lnr-eye"></span>
                <span>2.4K</span>
              </a>
            </li>
            <li>
              <a href="javascript:void(0);">
                <span class="lnr lnr-bubble"></span>
                <span>17.9K</span>
              </a>
            </li>
          </ul>
        </figure>
        <div class="tg-postcontent">
          <div class="tg-borderleft">
            <ul class="tg-posttags">
              <%post.tags.each do |tag|%>
                <li>
                  <%=link_to tag.name.capitalize, tag_path(tag)%>
                </li>
              <%end%>
            </ul>
            <div class="tg-posttitle">
              <h3>
                <%=link_to blog_path(post) do%>
                  <%=post.title.capitalize%>
                <%end%>
              </h3>
            </div>
          </div>
        </div>
      </article>
    </div>
    <%end%>
  </div>
</div>

app/views/shared/_rising.html.erb
<div class="tg-borderheading">
  <h3>What’s Rising</h3>
</div>
<div class="clearfix"></div>
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-7 col-lg-7">
    <%@big_risings.each do |post|%>
      <article class="tg-post">
      <figure class="tg-postimg">
        <span class="tg-postfeatured">
          <i class="fa fa-bolt"></i>
        </span>
        <%= image_tag post.image.url(:medium)%>
      </figure>
      <div class="tg-postcontent">
        <div class="tg-borderleft">
          <ul class="tg-posttags">
            <%post.tags.each do |tag|%>
              <li>
                <%=link_to tag.name.capitalize, tag_path(tag)%>
              </li>
            <%end%>
          </ul>
          <div class="tg-posttitle tg-posttitlelarge">
            <h3>
              <%=link_to blog_path(post) do%>
                <%=post.title.capitalize%>
              <%end%>
            </h3>
          </div>
        </div>
        <div class="tg-description">
          <p><%=truncate(post.description, length: 500, separator: ' ')%></p>
        </div>
        <ul class="tg-postmatadata">
          <li>
            <a href="javascript:void(0);">
              <span class="lnr lnr-eye"></span>
              <span>2.4K</span>
            </a>
          </li>
          <li>
            <a href="javascript:void(0);">
              <span class="lnr lnr-bubble"></span>
              <span>17.9K</span>
            </a>
          </li>
          <li>
            <a href="javascript:void(0);">
              <span class="lnr lnr-calendar-full"></span>
              <span><%=post.post_date%></span>
            </a>
          </li>
          <li>
            <a href="javascript:void(0);">
              <span class="lnr lnr-user"></span>
              <span>By: Josefine Shockley</span>
            </a>
          </li>
        </ul>
        <div class="tg-postbtnbox">
          <%=link_to "view post", blog_path(post), class: "tg-btn"%>
        </div>
      </div>
    </article>
    <%end%>
  </div>
  <div class="col-xs-12 col-sm-12 col-md-5 col-lg-5">
    <div class="tg-widget tg-widgettrendingposts">
      <div class="tg-widgetcontent">
        <ul>
          <%@other_risings.each do |post|%>
            <li>
              <figure>
                <%=link_to blogs_path(post) do%>
                  <%= image_tag post.image.url(:thumb)%>
                <%end%>
                <a class="tg-btnview" href="#"></a>
              </figure>
              <div class="tg-trendingpostcontent">
                <h4>
                  <%=link_to blogs_path(post) do%>
                    <%=post.title.capitalize%>
                  <%end%>
                </h4>
                <time datetime="2016-02-02"><%=post.post_date%></time>
                <span class="tg-postviews">2.4K Views</span>
              </div>
            </li>
          <%end%>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="tg-addbox">
  <a href="javascript:void(0);"><img src="images/placeholder/add-01-770x90.jpg" alt="image description"></a>
</div>
<div class="clearfix"></div>

app/views/shared/_slide.html.erb
<div class="tg-homebanner">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="row">
          <div id="tg-bannerfullwidthslider" class="tg-bannerfullwidthslider">
            <%@slide_shows.each do |slide|%>
              <article class="tg-post tg-postcononimg">
              <figure class="tg-postimg">
                <span class="tg-postfeatured"><i class="fa fa-bolt"></i></span>
                <%= image_tag slide.image%>
                <figcaption>
                  <div class="tg-postcontent">
                    <ul class="tg-posttags">
                      <li>
                        <%=link_to category_path(slide.category) do%>
                          <%=slide.category.category_name.upcase%>
                        <%end%>
                      </li>
                    </ul>
                    <div class="tg-posttitle tg-posttitlelarge">
                      <h3>
                        <%=link_to blog_path(slide) do%>
                          <%=slide.title.capitalize%>
                        <%end%>
                      </h3>
                    </div>
                  </div>
                  <div class="tg-postbtnbox">
                    <%=link_to "View All Post", blogs_path, class: "tg-btn"%>
                  </div>
                </figcaption>
              </figure>
            </article>
            <%end%>
          </div>
          <div class="tg-slicknavigation">
            <span class="tg-btnslicksquareprev"><i class="lnr lnr-arrow-left"></i></span>
            <span class="tg-btnslicksquarenext"><i class="lnr lnr-arrow-right"></i></span>
          </div>
          <div class="tg-bannerfullwidthslidecount"></div>
        </div>
      </div>
    </div>
  </div>
</div>