config/routes.rb
Rails.application.routes.draw do

    devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: "users/registrations"
    }

    # devise_for :admins, :controllers => { :registrations => :registrations }
    devise_for :admins, :skip => [:registrations]

    devise_scope :admin do
      get "/signin" => "devise/sessions#new", :as => "signin" # custom path to login/sign_in
    end

    devise_scope :user do
      get "/sign_in" => "devise/sessions#new", :as => "sign_in" # custom path to login/sign_in
      get "/sign_up" => "devise/registrations#new", :as => "sign_up" # custom path to login/sign_in
      get "users/verify/" => 'users/registrations#show_verify', as: 'verify'
      post "users/verify"
      post "users/resend"
    end

    as :admin do
      get 'admins/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'
      put 'admins' => 'devise/registrations#update', :as => 'admin_registration'
      patch 'admins' => 'devise/registrations#update', :as => 'update_admin_registration'
    end

    namespace :admin do
      root "dashboards#index"
      get 'dashboards' => "dashboards#index", :as => "dashboard"
      get 'invoices/:id' => 'orders#invoice', as: "invoice"

      resources :users
      resources :admins
      resources :categories
      resources :blogs
      resources :settings, only: [:index, :new, :update, :create, :edit]
    end

    get 'under_construction' => "static_pages#under_construction", as: "under_construction"
    root 'static_pages#index'
    resources :blogs, only: [:index, :show]
    resources :categories, only: [:index, :show]
    resources :tags, only: [:show]
end

app/models/setting.rb
class Setting < ApplicationRecord
  has_many :maintains
  accepts_nested_attributes_for :maintains, :allow_destroy => true
end

app/controllers/admin/settings_controller.rb
class Admin::SettingsController < ApplicationController
  before_action :authenticate_admin!
  def new
    @setting = Setting.new
    if Setting.any?
      redirect_to edit_admin_setting_url(Setting.first)
    else
      2.times do
        @maintain = @setting.maintains.build
      end
    end
  end

  def create
    @setting = Setting.new(setting_params)

    if @setting.save
      redirect_to edit_admin_setting_path(@setting)
    else
      render :new
    end
  end

  def edit
    if Setting.exists?
      @setting = Setting.find(params[:id])
      if !@setting.maintains.exists?
        2.times do
          @maintain = @setting.maintains.build
        end
      end
    else
      redirect_to new_admin_setting_path
    end
  end

  def update
    @setting = Setting.find(params[:id])

    if @setting.update(setting_params)
      redirect_to edit_admin_setting_url(@setting), notice: 'Successfully updated setting'
    else
      flash[:alert] = 'There was a problem updating setting'
  		render :edit
    end
  end

  private
    def setting_params
      params.require(:setting).permit!
    end
end

app/helpers/admin/settings_helper.rb
module Admin::SettingsHelper
end

app/views/admin/settings/_settings_form.html.erb
<div class="container">
  <%= simple_form_for ([:admin, @setting]) do |f|%>
    <div class="form-setting"  style="padding-top: 100px;">
      <div class="row">

          <div style="padding-top: 30px;">
            <%= f.fields_for :maintains do |maintain| %>

              <div class="form-group col-md-6">
                <%= maintain.select :option, Maintain::SELECT_PAGE, {prompt: "None"}, {:class=>"form-control"} %>
              </div>

              <div class="form-group col-md-6">
                <%= maintain.check_box :under_maintain%><br>
                <%= maintain.label :under_maintain%>
              </div>

            <%end%>
            <div class="form-group col-md-12 mt-10" style="margin-bottom: 284px;">
              <%=f.submit "Save", class: "btn btn-success"%>
              <%=link_to "Back",admin_dashboard_path, class: "btn btn-default"%>
            </div>
          </div>
      </div>
    </div>
  <%end%>
</div>

app/views/admin/settings/edit.html.erb
<%= render 'settings_form'%>

app/views/admin/settings/new.html.erb
<%= render 'settings_form'%>