config/routes.rb
Rails.application.routes.draw do

    devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: "users/registrations"
    }

    # devise_for :admins, :controllers => { :registrations => :registrations }
    devise_for :admins, :skip => [:registrations]

    devise_scope :admin do
      get "/signin" => "devise/sessions#new", :as => "signin" # custom path to login/sign_in
    end

    devise_scope :user do
      get "/sign_in" => "devise/sessions#new", :as => "sign_in" # custom path to login/sign_in
      get "/sign_up" => "devise/registrations#new", :as => "sign_up" # custom path to login/sign_in
      get "users/verify/" => 'users/registrations#show_verify', as: 'verify'
      post "users/verify"
      post "users/resend"
    end

    as :admin do
      get 'admins/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'
      put 'admins' => 'devise/registrations#update', :as => 'admin_registration'
      patch 'admins' => 'devise/registrations#update', :as => 'update_admin_registration'
    end

    namespace :admin do
      root "dashboards#index"
      get 'dashboards' => "dashboards#index", :as => "dashboard"
      get 'invoices/:id' => 'orders#invoice', as: "invoice"

      resources :users
      resources :admins
      resources :categories
      resources :blogs
      resources :settings, only: [:index, :new, :update, :create, :edit]
    end

    get 'under_construction' => "static_pages#under_construction", as: "under_construction"
    root 'static_pages#index'
    resources :blogs, only: [:index, :show]
    resources :categories, only: [:index, :show]
    resources :tags, only: [:show]
end

app/models/category.rb
class Category < ApplicationRecord
  before_save :update_slug

  has_many :blogs
  belongs_to :admin

  def update_slug
    self.slug = category_name.parameterize
  end

  def to_param
    slug
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :authenticate_admin!
  before_action :admin_only?, except: [:index]

  def index
    @category = current_admin.categories.build
    @categories = Category.all
  end

  def show
    @category = Category.find_by_slug(params[:id])
  end

  def new

  end

  def create
    @category = current_admin.categories.build(category_params)
    if @category.save
      respond_to do |format|
        flash.now[:notice] = "Successful Created"
        format.html { redirect_to admin_categories_path }
        format.js
      end
    else
      respond_to do |format|
        flash.now[:alert] = "Please fill the field blank or category Duplicated"
        format.html { redirect_to admin_categories_path }
        format.js { render template: "admin/categories/category_error.js.erb" }
      end
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find_by_slug(params[:id])
    if @category.update(category_params)
      respond_to do |format|
        flash.now[:notice] = "Successful Updated"
        format.html { redirect_to admin_categories_path }
        format.js
      end
    else
      respond_to do |format|
        flash.now[:alert] = "Please fill the field blank or category Duplicated"
        format.html { redirect_to admin_categories_path }
        format.js { render template: "admin/categories/category_error.js.erb" }
      end
    end
  end

  def destroy
    @category = Category.destroy(params[:id])
    respond_to do |format|
      flash.now[:error] = "Delete"
      format.html { redirect_to admin_categories_url }
      format.js
    end
  end

  private
    def admin_only?
      unless  current_admin.admin?
        unless @admin == current_admin
          redirect_to admin_dashboard_path, alert: "Access Denied"
        end
      end
    end

    def category_params
      params.required(:category).permit!
    end
end

app/controllers/categories_controller.rb
class CategoriesController < FrontEndApplication
  def index

  end

  def show
    @populars = Blog.all.order("created_at desc").limit(6)
    @category  = Category.find_by_slug(params[:id])
    @categories = Category.all
    @other_risings = Blog.not_show_first_record
    @editor_picks = Blog.all.order(:created_at).limit(3)
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/views/admin/categories/_category.html.erb
<tr class="delete_category_<%=category.id%>">
  <td id="data_<%=category.id%>">
    <%=category.id%>
  </td>
  <td>
    <%=category.category_name%>
  </td>
  <td>
    <%=time_ago(category.created_at)%>
  </td>
  <td class="text-center">
    <%=form_for([:admin, category], remote: true) do |f|%>
      <%=link_to admin_category_path(category), remote: true,class: "btn btn-primary", "data-target" => "bd-example-modal-lg-panhara" do %>
        View
      <%end%>
      <%=link_to edit_admin_category_path(category.id),id: "link_#{category.id}",class: "btn btn-primary", remote: true do %>
        Edit
      <% end %>
    <%end%>
  </td>
</tr>

app/views/admin/categories/_category_form.html.erb
<%=simple_form_for([:admin, @category], remote: true) do |f|%>
  <div class="form-row">
    <div class="form-group col-md-12">
      <label>Category Name</label>
      <%=f.text_field :category_name, class: "form-control"%>
    </div>

    <div class="form-group col-md-12">
      <%=f.submit "Save User", class: "btn btn-primary"%>
      <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    </div>
  </div>
<%end%>

app/views/admin/categories/_edit.html.erb
<%=content_tag :div, class: "modal fade bd-example-modal-lg", id: "edit_#{dom_id(@category, :modal)}" do%>
  <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <div class="row">
          <div class="col-md-12">
            <h5 class="m-b-0">Edit User</h5>
          </div>
        </div>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%=simple_form_for([:admin, @category], remote: true) do |f|%>
        <div class="modal-body overflow-auto">
          <div class="form-row">
            <div class="form-group col-md-12">
              <label>Category Name</label>
              <%=f.text_field :category_name, class: "form-control"%>
            </div>
          </div>
        </div>
        <div class="modal-footer justify-content-start">
          <%=f.submit "Update", class: "btn btn-primary"%>
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      <%end%>
    </div>
  </div>
<%end%>

app/views/admin/categories/_show.html.erb
<%=content_tag :div, class: "modal fade bd-example-modal-lg", id: "detail_#{dom_id(@category, :modal)}" do%>
  <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="myLargeModalLabel">Large Modal</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <h3>I'm large modal</h3>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipisicing elit.
          Aspernatur, assumenda aut eaque eius error, eum expedita iusto nobis
          obcaecati, perspiciatis quae quos saepe similique! Iure non
          perspiciatis qui veniam vitae!
        </p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">
          Close
        </button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
<%end%>

app/views/admin/categories/category_error.js.erb
$("input#category_email").val("");
$("#category-errors").html("<br><%= j render partial: 'layouts/flash_errors', locals: {flash: :flash}%>");

app/views/admin/categories/category_success.js.erb
$("input#category_category_name").val("");
$("#category-success").html("<br><%= j render partial: 'layouts/flash_success', locals: {flash: :flash}%>");

app/views/admin/categories/create.js.erb
$("input#category_category_name").val("");
$(".disabled").attr("disabled", false)
$("#category-errors").html(" ");
$("#category-success").html("<%= custom_flash_message%>");
$("#category-index").append("<%=escape_javascript render(@category)%>");

$(function() {
  $('.delete_category_<%=@category.id%>').submitOnCheck();
});

$('.delete_category_<%=@category.id%>').submitOnCheck();

app/views/admin/categories/destroy.js.erb
$('.delete_category_<%=@category.id%>').remove();

app/views/admin/categories/edit.js.erb
$('body').append('<%= j render partial: "admin/categories/edit"%>');
$('#edit_<%= dom_id @category, :modal%>').modal('toggle');
$("#edit_category").text("Edit Category");
$('tr').find('td:nth-child(2)').each(function(){
  if ($(this).text().trim() == "<%=@category.category_name%>") {
    $(this).parent().addClass("edit_row_<%=@category.id%>")
  }
});

app/views/admin/categories/index.html.erb
<%=render "admin/shared/aside"%>
<main class="admin-main">
   <!--site header begins-->
   <%=render "admin/shared/header"%>
   <!--site header ends -->
   <section class="admin-content">
      <div class="container">
      <div class="row m-t-30">
         <div class="col-md-auto col">
            <div class="kanban-item" style="margin-bottom: 0px;">
               <a class="kanban-item-title btn btn-primary" style="color: #fff;">
               <i class="mdi mdi-plus-circle-outline"></i>
               Add Category
               </a>
            </div>
         </div>
      </div>
      <!-- Content -->
      <div class="row">
         <div class="col-md-12">
            <div class="card m-b-30 m-t-30">
               <div class="card-header">
                  <h5 class="m-b-0">
                     <i class="mdi mdi-checkbox-intermediate"></i> Categories
                  </h5>
               </div>
               <div class="card-body">
                  <div class="table-responsive">
                     <table class="table table-hover align-td-middle">
                        <thead>
                           <tr>
                              <th>#</th>
                              <th>Category Name</th>
                              <th>Created_At</th>
                              <th class="text-center">Action</th>
                           </tr>
                        </thead>
                        <tbody id="category-index">
                           <%if @categories.any?%>
                           <%= render @categories%>
                           <%end%>
                        </tbody>
                     </table>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <!-- Modal -->
   </section>
</main>
<div class="modal fade bd-example-modal-lg" id="kanbanItemModal" tabindex="-1" role="dialog" aria-hidden="true">
   <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
      <div class="modal-content">
         <div class="modal-header">
            <div class="row">
               <div class="col-md-12">
                  <h5 class="m-b-0">Create User</h5>
               </div>
            </div>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
         </div>
         <div class="modal-body overflow-auto">
            <div id="categorys">
               <div id="category-errors"></div>
               <div id="category-success"></div>
               <%=render partial: "category_form", locals: {category: @category}%>
            </div>
         </div>
      </div>
   </div>
</div>

app/views/admin/categories/show.js.erb
$('body').append('<%= j render partial: "admin/categories/show"%>');
$('#detail_<%= dom_id @category, :modal%>').modal('toggle');

app/views/admin/categories/update.js.erb
$("#category-success").html("<br><%= j render partial: 'layouts/flash_success', locals: {flash: :flash}%>");
$(".edit_row_<%=@category.id%>").find('td:nth-child(2)').text("<%=@category.category_name%>").next().text("<%=time_ago(@category.created_at)%>")